### ISSUE TITLE
WS280 27:uniprotxrefs.pl script fails repeatedly

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#150]
In the latest builds, this file seems to have been produced intermittently

[mz3@noah-login-01 logs]$ wc -l /nfs/panda/ensemblgenomes/wormbase/DATABASES/WS2*/REPORTS/elegans.uniprot_papers.txt
The log shows that the script has failed repeatedly, and tried to re-start itself  cat /nfs/nobackup/ensemblgenomes/wormbase/scratch/BUILD/LSF_OUT/elegans/uniprotxrefs.pl.elegans.lsfout

Root cause:
-Script fails silently during build
-Existance of file is not checked for in FTP generation
-May be some issue with how the script is written that is causing it to fail.

**Action:**
Make sure the script gives error in the log file if it fails
Try to see if we can work out why it fails.
Check the runlog if the script was run for 274 and 275 (to see if that is why it failed)

Test:

**Comment by markquintontulloch** [comment]
The script was not run for WS274 and WS275.

The log given above doesn't show the script restarting itself - the log in the scratch dir is a concatenation of runs from different builds and only the last entry corresponds to the WS280 build.

The pre_FTP_dumps.pl script does already check the output of the uniprotxrefs.pl script - it checks for the presence of a file and that the file is not empty.  It also checks that the script exited with zero status.  However, upon finding any of these errors it only writes a message to the log with the prefix 'WARNING:' - it does not use the $log->error function which would cause the log email to have an 'ERROR' heading.

The previous runs of uniprotxrefs.pl were exiting with error code 13.  This was due to the Ace DB handle not being explicitly closed, although the script had otherwise worked correctly and completed.

**Action:**
Implement logging with error function of Log_files for clearer reporting of issues. 
Explicitly close database handle to prevent exit code 13.
