### ISSUE TITLE
WS280 32:  XML file does not validate

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#153]
Running the script upload_empc_links.pl the final files do not validate as valid XML files.

/nfs/production/panda/ensemblgenomes/wormbase/BUILD/autoace/acefiles/Wormbase_links.xml.gz

/nfs/production/panda/ensemblgenomes/wormbase/BUILD/autoace/acefiles/Wormbase_provider.xml.gz

With the same script, we also cannot connect to the ftp server using the credentials in ebi_resources/EPMCFTP.s

noah-login-02[wormbase]5019: ftp labslink.ebi.ac.uk
Connected to labslink.ebi.ac.uk (193.62.194.179).
220-Private FTP
220
Name (labslink.ebi.ac.uk:wormbase): elinks
421 Service not available, remote server has closed connection
Login failed.
No control connection for command: Transport endpoint is not connected

Documentation: http://europepmc.org/LabsLink

Action: Check Europe PMC the format and submission guidelines what they need. Re-write the script to give them what they want.
Test: by submitting WS280 data.

**Comment by markquintontulloch** [comment]
There was a bug meaning that the Tablemaker query was not getting printed to the .def file.  As such an empty XML template was being generated, which did not validate as at least one entry is required.  The bug was fixed and validation reimplemented with commit [f8e3561](https://github.com/WormBase/wormbase-pipeline/commit/f8e35610eac3293dad932c4f75412822b31c874d).  WS280 data was successfully submitted.
