### ISSUE TITLE
WS280 33:  script fails to get the get_wormbase_version_name

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#154]
perl $CVS_DIR/autoace_builder.pl -public  fails in the get_wormbase_version_name subroutine from WormBase.pm

It had to be hacked to set it to the right value. Not sure if this issue can be reproduced.

Action: Check that script works as expected.

**Comment by Paul-Davis** [comment]
I think this has always been the case because the file needed for the build version gets moved from under autoace -> DATABASES/WSrel by the script as it's running. Also the log dir gets removed at the same time which also causes an issue.

Maybe we can add a couple of steps post move to reinstate the logs dir and the file needed for the build version prior to it's reuse by the script.
