### ISSUE TITLE
Syncing data with VEP

### ISSUE THREAD

**Issue by MagdalenaZZ** [WormBase/wormbase-pipeline#192]
Variation WBVar00000031  was curated as  W(355) to stop, yielding the substitution "gg" to "rr". However, in this case, VEP might not interpret it properly, as the output looks like this:

Variation : "WBVar00000031"
Evidence         Paper_evidence "WBPaper00004714"
Public_name      "ad541"
HGVSg    ""
Sequence         "F52A8"
Flanking_sequences       "cggcgagctgggattgcacaattcgcattt" "gcttgattatttaatattaatttttctctt"
Mapping_target   "F52A8"
Substitution     "gg" "rr"
Sequenced
Allele
Species  "Caenorhabditis elegans"
Strain   "WBStrain00005480"
Strain   "WBStrain00005517"
Laboratory       "DA"
Live
Gene     "WBGene00001680" Amber_UAG_or_Opal_UGA "W(355) to stop" Paper_evidence "WBPaper00004714"
Transcript       "F52A8.2a.1" Coding_exon
Transcript       "F52A8.2a.1" VEP_consequence "coding_sequence_variant"
Transcript       "F52A8.2a.1" VEP_impact "MODIFIER"
Transcript       "F52A8.2a.1" cDNA_position "1240-1241"
Transcript       "F52A8.2a.1" CDS_position "1103-1104"
Transcript       "F52A8.2a.1" Protein_position "368"
Transcript       "F52A8.2a.1" Exon_number "9\/10"
Transcript       "F52A8.2a.1" Codon_change "tGG\/tRR"

Whereas, what I would expect is output to look more like this - explicitly stating "stop_gained" and W21stop:
203275  Gene     "WBGene00006745"
203276  Transcript       "B0273.4f.1" Amber_UAG "W to amber stop (21)"
203277  Transcript       "B0273.4f.1" Coding_exon
203278  Transcript       "B0273.4f.1" VEP_consequence "stop_gained"
203279  Transcript       "B0273.4f.1" VEP_impact "HIGH"
203280  Transcript       "B0273.4f.1" HGVSc "B0273.4f.1:c.62G>A"
203281  Transcript       "B0273.4f.1" HGVSp "CE49300.1:p.Trp21Ter"
203282  Transcript       "B0273.4f.1" cDNA_position "62"
203283  Transcript       "B0273.4f.1" CDS_position "62"
203284  Transcript       "B0273.4f.1" Protein_position "21"
203285  Transcript       "B0273.4f.1" Exon_number "1\/4"
203286  Transcript       "B0273.4f.1" Codon_change "tGg\/tAg"
203287  Transcript       "B0273.4f.1" Amino_acid_change "W\/*"

Because of the ambiguity in the protein to DNA translation above - VEP might be conservative, and does not predict the right consequence (right as in the one cited by the paper).

Recommended actions:
1. Extend the variants model to allow for publication-reported amino acid change
2. "Force" VEP to evaluate the right protein-coding change by resolving ambiguous gg->rr to one of the alternatives which produces a stop codon, eg gg->ag or gg->ga. That way the consequence will remain true to the publication, and not "erase" the result of stop-codon introduced.
3. Alternatively, in the model replace gg-> rr with gg->ag,ga and then get VEP to understand that

**Comment by sdiamantakis** [comment]
This is indeed tricky. Paper states that  Trp (W) changes into Stop
![image](https://user-images.githubusercontent.com/70586981/129238077-7a7d817e-5d3f-4d17-b01e-52c3a2d35d35.png)
When curated as now, gg rr,  the 4 possible changes can cover all stops and Trp itself, which is not right.
Trp can change to Stop in 3 ways:
TGG (Trp) to TAG(Amber) => TG/AG) so G=>A
or TGG to TAA (Ochre) => TG/AG/A so GG=>AA
or TGG to TGA (Opal) => TGG/A so G => A
If I read codon usage table correctly (from https://www.ncbi.nlm.nih.gov/books/NBK20194/)
the most often used stop codons in elegans are TAA and TAG
therefore I would correct the substitution entry from ‘gg rr’ to ‘gg ar’ to cover 2 most prevalent stop codons (Amber and Ochre). BTW,  tags like that (Amber_UAG, Ochre_UAA, Opal_UGA, Ochre_UAA_or_Opal, Amber_UAG_or_Ochre_UAA, Amber_UAG_or_Opal_UGA) were in use  in #Molecular change until we deprecated it recently.
Anyway, If we ever encounter the evidence that this change is in fact TGA we will correct the entry to g a and move flanks accordingly.
Also, I think that the best solution would be to curate it as a “tgg stop”   I can see that I am able to enter and save ‘stop’ in acedb but I am not sure if other scripts in our pipelines would accept it as a valid entry.

**Comment by markquintontulloch** [comment]
I think the best solution for this is to expand the possible base combinations in the pre-processing for the VEP pipeline.  In this case, that would give 4 alternative alleles - AA,AG,GA,GG  In this case one of those alleles matches the reference allele, so the VEP would ignore that and we would have 3 rows of output in the VEP for each transcript that the variant overlaps.

However, having multiple consequences for each variant/transcript pairing doesn't fit with the WormBase model.  As such, my proposal would be to pick the worst consequence for storing in AceDB (in the case of equally bad consequences, the first one would be picked) - the particular allele that was picked would be reflected in the Codon_change tag.

**Comment by markquintontulloch** [comment]
Conversation from Slack:

**Mark Quinton-Tulloch** 
Just to note, the reason for the 'MODIFIER' status for VEP impact is that this is the default when the coding sequence is unknown.

**Magdalena Zarowiecki**  
Yes, I think for the gg->gg change it is not compatible with the original data (W->Stop) so we don't need to consider it. The 3 other versions all yield W->Stop, so they [should] have identical consequences in VEP? 
But I do think we need to fix up the model to hold this data in an appropriate way, so that VEP can then do the right thing with it

**Mark Quinton-Tulloch** 
We could shoehorn the data into the existing model by using delimited lists for all the fields that would be affected (HGVSg/c/p names, impact, modifier, SIFT and PolyPhen scores and predictions).  The problem with this (which would also be an issue were we to change the model) is that display of this gets very messy as it only takes a few ambiguous bases in an inserted sequence for the number of permutations to balloon.
My gut feeling is that people only really care about the most severe consequence.  The solution I proposed above is easily implemented and doesn't affect anything downstream of the VEP pipeline, whereas any model changes might require some significant rework both in the VEP pipeline, in the GFF and VCF generation script, and in the front end display. 
One downside to this approach is that it is possible that if one of these variations with ambiguous bases were to affect multiple transcripts, the most severe consequence would not necessarily be caused by the same permutation of the allele for each transcript.  This would only affect the HGVSg ID, as this is a property of the affected gene and not the affected transcript.  I suspect that this is an edge case of an edge case though, so probably not worth losing too much sleep over.

**Comment by markquintontulloch** [comment]
I've implemented my proposed solution with this commit: [e8d0465](https://github.com/WormBase/wormbase-pipeline/commit/e8d04659672b1091809cf4b58f40a1adec8971f4)

The final solution has not yet been decided, so further code/model changes may be required.

@MagdalenaZZ - if you think that this approach is sufficient then you can close this ticket.

**Comment by MagdalenaZZ** [comment]
Thank you!
