### ISSUE TITLE
Datomic Migration on Codon

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#210]
Need to work out what software needs to be ported over to the codon cluster so that we can perform the datomic migration (WS283_test possibly).

noah:
/nfs/panda/ensemblgenomes/wormbase/software/packages/

codon:
/hps/software/users/wormbase/shared/

Things like these concern me:
```
drwxrwxr-x   6 wormbase nucleotide     4096 Apr 11  2015 jre1.7.0_80
drwxrwxr-x   7 wormbase nucleotide     4096 Jul 29  2015 datomic-free-0.9.5206
drwxrwxr-x   8 wormbase nucleotide     4096 Aug  4  2015 jdk1.8.0_60
lrwxrwxrwx   1 wormbase nucleotide       11 Sep  8  2015 java8 -> jdk1.8.0_60
drwxrwxr-x   4 wormbase nucleotide     4096 Oct 13  2015 edn-perl
drwxrwxr-x   3 wormbase nucleotide     4096 Oct 15  2015 datomic
```

@mluypaert is this something that you can fit between AGR scrum 👍

**Comment by Paul-Davis** [comment]
These might all be red herrings and as the migration is performed exclusively on AWS we don't require any?

**Comment by mluypaert** [comment]
> These might all be red herrings and as the migration is performed exclusively on AWS we don't require any?

I think you're right, these are all mostly irrelevant to the datomic migration, as that is fully happening on AWS (and all required tools are installed on that EC2 instance). However, in order to be able to connect to that instance (from codon) there are a few requirements:
 * The AWS CLI must be installed and available on codon. On noah, this currently seems to be loaded through the datomic_build module, by including `~/.local/bin` in your PATH (which seems to be where aws is installed on noah).
 * The SSH key file currently accessible to the wormbase user (`.ssh/datomic_build`) must also be made accessible to the wormbase user on codon (assuming we're still using a wrombase user like that on codon), in order to be able to SSH into the AWS machine.

However, the current instructions for connecting to the AWS instance don't seem to add up for me (trying to follow them results in errors), so I'll need to follow along with you (@Paul-Davis) or @sdiamantakis to see how you do the whole process from the start to see where all required modules and files come in play. It seems like the AWS profiles got jumbled up in the wormbase user to allow the documented instructions to work as intended (as far as I understand), but seem like it's been like that since Februari, so I'm guessing you have a slightly different approach at connecting in reality (since successful builds have been completed since).

**Comment by Paul-Davis** [comment]
I have tested my credentials and can retrieve the status of the ec2 machine.
