### ISSUE TITLE
phenotype_info class Strain connection

### ISSUE THREAD

**Issue by Paul-Davis** [WormBase/wormbase-pipeline#44]
I need a different strain tag in the phenotype_info class to capture
the strain containing the allele, transgene, or rearrangement to which
the phenotype is attached.  This will also allow propagation to the
strain pages without duplicating phenotypes up to the strain as well.

**Comment by kyook** [comment]
Ok. This request is no longer needed.  As you pointed out there is a preexisting tag that will work. Phenotype_info  Strain ?Strain. 

I don't know if it will cause a problem that the same tag is used in the Phenotype model.  It shouldn't since these I can't see where these tags would be used at the same time, but if you think it would be a problem, then a fix would be to change the tag name in Phenotype_info to something else.

**Comment by Paul-Davis** [comment]
If you are happy using this tag, then I will close the issue, thanks for resolving.

P
