### ISSUE TITLE
C elegans genome build version names

### ISSUE THREAD

**Issue by sravanthinsp** [WormBase/wormbase-pipeline#73]
I am new to bioinformatics and working with genome sequences. 
I have recently used a bioinformatics platform to map a mutant. They have used ce11 version as reference genome. Is ce11 same as WBcel235? 
How do I know what each genome build is called?

**Comment by epaule** [comment]
have a look in http://www.wormbase.org/about/Frequently_asked_questions under UCSC Version/Access. There is a table with the equivalence between UCSC and WormBase version.
Combined with: http://www.wormbase.org/species/c_elegans , you can see that the WBcel235 is the current assembly since WS235, so as Ce11 is WS245 it used the same assembly.
